spring.application.name=CoffeeBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/coffeedb
spring.datasource.username=postgres
spring.datasource.password=Srini@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9080
