spring.application.name=CoffeeBackend

# =========================
# DATABASE
# =========================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Don't keep unnecessary Hibernate statistics
spring.jpa.properties.hibernate.generate_statistics=false

# =========================
# SERVER
# =========================

server.port=${PORT:9080}